### ISSUE TITLE
Can't copy JSX on website

### ISSUE THREAD

**Issue by jmpp** [tailwindlabs/heroicons.com#132]
## Bug description 

When I try to click on the "Copy JSX" button, it will copy the SVG instead.

## How to reproduce

- Simply go to the webpage and hover an icon to make the two buttons `Copy SVG` and `Copy JSX` appear.
- Click on `Copy JSX`
- The SVG code is copied into the clipboard.

Tested under a Chromium Version 102.0.5005.115 (Official build) (64 bits), on Windows.

Thank you for reading :)

**Comment by adamwathan** [comment]
Hey! I think you're confused, it does copy JSX:

```
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
  <path strokeLinecap="round" strokeLinejoin="round" d="M4.26 10.147a60.436 60.436 0 00-.491 6.347A48.627 48.627 0 0112 20.904a48.627 48.627 0 018.232-4.41 60.46 60.46 0 00-.491-6.347m-15.482 0a50.57 50.57 0 00-2.658-.813A59.905 59.905 0 0112 3.493a59.902 59.902 0 0110.399 5.84c-.896.248-1.783.52-2.658.814m-15.482 0A50.697 50.697 0 0112 13.489a50.702 50.702 0 017.74-3.342M6.75 15a.75.75 0 100-1.5.75.75 0 000 1.5zm0 0v-3.675A55.378 55.378 0 0112 8.443m-7.007 11.55A5.981 5.981 0 006.75 15.75v-1.5" />
</svg>
```

Notice the attributes like `strokeWidth` instead of `stroke-width`, which are the JSX versions of those attributes.

It doesn't copy the component you'd get from the React library like `<AcademicCap />` if that's what you're expecting, but that's not the intended behavior. At Tailwind Labs we inline these icons almost exclusively and don't use the libraries, so we added this feature for our own benefit 🙂

**Comment by jmpp** [comment]
Thank you for your quick answer. You're right, I was tricked by getting the `<svg …` tag and didn't notice the props at all.

I expected indeed to get the component name from the `@heroicons/react` package.

Sorry for the inconvenience, and thank you for the detailed answer 🙂
