### ISSUE TITLE
Copy JSX button copies svg element 

### ISSUE THREAD

**Issue by Moeinmn** [tailwindlabs/heroicons.com#172]
The Copy JSX button copies an svg element 
```
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
  <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 4.5l15 15m0 0V8.25m0 11.25H8.25" />
</svg>

```
It better to return the actual JSX element instead of svg element : 
`<BeakerIcon className="h-6 w-6 text-blue-500" />`

**Comment by adamwathan** [comment]
Hey! It copies the SVG as JSX, it's not meant to copy the React component name. See previous issue:

https://github.com/tailwindlabs/heroicons.com/issues/132#issuecomment-1235374255

The problem it's designed to solve is copying the SVG to paste inline in a React project, where pasting raw SVG won't work because all of the attributes will be dash-case instead of camelCase like they need to be.
